apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: sample-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          i=0
          while true; do
            echo "{\\"level\\":\\"info\\",\\"message\\":\\"Log entry \\$i from log-generator\\",\\"timestamp\\":\\"\\$(date -u +%Y-%m-%dT%H:%M:%SZ)\\",\\"app\\":\\"log-generator\\"}"
            i=\\$((i+1))
            sleep 5
          done
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: sample-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: sample-apps
spec:
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80