apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  releaseName: gatekeeper
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  values:
    replicaCount: 1   # recommended for HA