apiVersion: v1
kind: Namespace
metadata:
  name: demo-apps

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-apps

---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno

---
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system