apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworksecuritygroup-azure
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XNetworkSecurityGroup

  patchSets:
    - name: common
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.location"
          toFieldPath: "spec.forProvider.location"

        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroupName"
          toFieldPath: "spec.forProvider.resourceGroupName"

        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.tags"
          toFieldPath: "spec.forProvider.tags"

  resources:
    - name: nsg
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: NetworkSecurityGroup
        spec:
          providerConfigRef:
            name: default
          forProvider:
            securityRule:
              - name: allow-ssh
                priority: 100
                direction: Inbound
                access: Allow
                protocol: Tcp
                sourcePortRange: "*"
                destinationPortRange: "22"
                sourceAddressPrefix: "*"
                destinationAddressPrefix: "*"
      patches:
        - type: PatchSet
          patchSetName: common
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "metadata.labels[crossplane.io/parent-uid]"